# Secrets File
name: Hello World push&pull-req
on: 
push:
  branches:
    - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Build step
      run: echo "Hello ${{secrets.MY_DOCKER_PWD}}"
