name: Env at workflow level

on: workflow_dispatch

env:
  APP_ENV: Dev

jobs:
  env_demo:
    runs-on: ubuntu-latest
    env:
      APP_ENV: TEST

    steps:
      - name: Show Env
        env:
          APP_ENV: PROD
        run: echo "App is connecting to $APP_ENV"
